import logging
from typing import Dict, Any, Optional
from services.gemini_client import gemini_client

logger = logging.getLogger("final_validator")

FINAL_VALIDATOR_SYSTEM_PROMPT = """
You are the Final Story Validator Agent.
Your responsibility is to audit the narrative prose generated by the Writer Agent against the original Story Bible and user intervention.

AUDIT CHECKS:
1. Grounded Entities: Did the story stay within the characters, locations, and world rules of the Story Bible? Flag any sudden unrelated characters (e.g. Captain Herrera, Dolores Vega) or foreign settings (e.g. Caymans, Yucatán).
2. Occupation Integrity: Is the protagonist still working in their established occupation (e.g. Elias is still a lighthouse keeper, NOT a charter boat captain or smuggler)?
3. Intervention Execution: Did the story actually enact the user's intervention?
4. Causal Coherence: Are the unfolding scenes consistent with the alternate timeline?

INSTRUCTIONS:
Produce a valid JSON object containing:
1. `is_valid`: Boolean (True if properly grounded; False if major hallucinations or occupation shifts occurred).
2. `hallucinations_detected`: Array of ungrounded entities or role shifts.
3. `remediation_notes`: Instructions for rewriting if `is_valid` is False.
4. `summary`: 1-2 sentence assessment.

Return ONLY the JSON object.
"""

class FinalValidator:
    async def validate_story(
        self,
        story_text: str,
        intervention: str,
        story_bible: Dict[str, Any],
        divergence_data: Dict[str, Any],
        api_key: Optional[str] = None
    ) -> Dict[str, Any]:
        prompt = f"""
USER INTERVENTION: "{intervention}"

STORY BIBLE ANCHORS:
Characters & Roles: {story_bible.get('character_roles')}
Locations: {story_bible.get('locations', [])}
World Rules: {story_bible.get('world_rules', [])}

DIVERGENCE PLAN:
Title: {divergence_data.get('divergence_title')}
Timeline: {[e.get('title') for e in divergence_data.get('alternate_timeline', [])]}

GENERATED STORY PROSE TO AUDIT:
---
{story_text[:4000]}
---

Audit this generated story. Return valid JSON.
"""
        try:
            result = await gemini_client.generate_json(
                prompt=prompt,
                system_instruction=FINAL_VALIDATOR_SYSTEM_PROMPT,
                temperature=0.1,
                override_api_key=api_key
            )
            return result
        except Exception as e:
            logger.error(f"Final validation error: {e}")
            return {
                "is_valid": True,
                "hallucinations_detected": [],
                "remediation_notes": "",
                "summary": "Passed with default fallback."
            }

final_validator = FinalValidator()
